hawtio/hawtio-next

craco.config.js
package.json
src/hawtio/help/registry.test.ts
src/hawtio/test/support.ts

* craco.config.js
* Removes need for config parameter
* Adds src/hawtio/test module to directories
* Adds moduleNameMapper for react-markdown which was throwing an error on use of "export" token"
* package.json
* Adds script for test coverage
* **/.ts
* Adds support module for testing. Include any functions required by number of tests
* Moves the mocking of global.fetch to its own function and adds handling for replacing with any default after tests are completed

(#11): Small changes to jest configuration

---

packages/hawtio/package.json
packages/hawtio/src/help/HawtioHelp.tsx
packages/hawtio/src/plugins/connect/index.ts
packages/hawtio/src/plugins/jmx/JmxContent.tsx
packages/hawtio/src/plugins/jmx/index.ts
packages/hawtio/src/preferences/HawtioPreferences.tsx
packages/hawtio/src/ui/page/HawtioPage.tsx
yarn.lock

This is a WIP PR. I've currently migrated and refactored all (I hope) routes in all plugins except camel.
Thinks to do: 
- migrate camel plugin,
- configure local dev environment to auto redirect to [host]/hawtio, this was removed in router v6
@tadayosi  please check if applicable so far

feat: React router migration

---

packages/hawtio/src/plugins/camel/routes-service.test.ts
packages/hawtio/src/plugins/camel/routes-service.ts
packages/hawtio/src/util/xml.ts

* Uses browser native DOM Parser instead.
* Adds parsing function to its own function to allow for other implementations to be dropped in at later date if required

feat(camel): Replaces jquery xml parser

---

packages/hawtio/src/plugins/jmx/JmxTreeView.tsx

Search on JMX tree and highlight of selected node.
Tree search functionality is as follows:
- If parent node is a hit bring the parent node completely.
- If parent node is not a hit but any subnodes are hits, return the parent with only the subnodes that are hits. (Subnodes follow the same rule as above).
- If there are no hits in parent or subnodes, it's not shown.
@phantomjinx  I saw that you did one search functionality and put it in the class JMBeanTree. Would you like me to update it? Right now yours wont retrieve children nodes on parent hits.
|-> Will be setting up a PR in the future refactoring this code to the general case for both JMX and Camel
Also another gif showing the highlight in action 
Fixed the issue with the broken yarn build with @tadayosi …

Search on JMX tree (Fixes #24 and #72)

---

packages/hawtio/src/plugins/camel/CamelContent.tsx
packages/hawtio/src/plugins/camel/camel-content-service.ts
packages/hawtio/src/plugins/camel/contexts/Contexts.tsx
packages/hawtio/src/plugins/camel/type-converters/TypeConverters.css
packages/hawtio/src/plugins/camel/type-converters/TypeConverters.tsx
packages/hawtio/src/plugins/camel/type-converters/TypeConvertersStatistics.test.tsx
packages/hawtio/src/plugins/camel/type-converters/TypeConvertersStatistics.tsx
packages/hawtio/src/plugins/camel/type-converters/index.ts
packages/hawtio/src/plugins/camel/type-converters/type-converters-service.test.tsx
packages/hawtio/src/plugins/camel/type-converters/type-converters-service.ts
packages/hawtio/src/plugins/connect/jolokia-service.ts

* jolokia-service
* View that requires a writeAttribute function so implemented in same style as the 'read' function
* Contexts
* Narrows the context to use the CamelContext rather than the more general plugin context. Allows for fewer imports when running jest unit tests

feat(#145): Provides TypeConverters view

---

packages/hawtio/src/plugins/jmx/JmxTreeView.tsx
packages/hawtio/src/plugins/shared/tree/tree.ts

The logic should work but as in https://github.com/hawtio/hawtio-next/pull/160 I'm unable to get yarn start to start the instance after build finishes successfully so I couldn't do a final test. I'm setting it up as a draft and will continue in Tuesday

refactor(MBeanTree): refactored code so both JMX and camel components have the same search behaviour

---

packages/hawtio/src/plugins/camel/CamelPreferences.tsx
packages/hawtio/src/plugins/camel/camel-preferences-service.test.ts
packages/hawtio/src/plugins/camel/camel-preferences-service.ts
packages/hawtio/src/plugins/camel/camel-preferences-storage-service.ts
packages/hawtio/src/plugins/camel/index.ts

This together with #191 completes #41 
Notes:
- Right now values are being saved to local storage and little else. Would like to get your input in if any components already exist to put the wiring on them.
- Reset button. Should I add it? Home preferences didn't have a Reset button before and it has it, same for Jolokla settings. I guess it's a yes but wanted to confirm.
- Hint icons. I saw we dropped this from other preferences pages. Should I file a separate issue to implement them on all preferences pages?
- Overuse of arrow functions on the component: trying to reduce the amount of duplicated code for type checking, I had to use arrow functions because I lose the "this" when passing them as parameters. Is not too much boilerplate... until prettier comes up and puts everything in …

feat(#41): Camel preferences

---

packages/hawtio/src/plugins/camel/CamelTreeView.tsx
packages/hawtio/src/plugins/camel/context.ts
packages/hawtio/src/plugins/connect/ConnectPreferences.tsx
packages/hawtio/src/plugins/connect/jolokia-service.ts
packages/hawtio/src/plugins/jmx/JmxTreeView.tsx
packages/hawtio/src/plugins/jmx/context.ts
packages/hawtio/src/plugins/shared/globals.ts
packages/hawtio/src/plugins/shared/tree/node.test.ts
packages/hawtio/src/plugins/shared/tree/node.ts
packages/hawtio/src/plugins/shared/tree/tree.test.ts
packages/hawtio/src/plugins/shared/tree/tree.ts
packages/hawtio/src/plugins/shared/workspace.ts
packages/hawtio/src/util/strings.test.ts
packages/hawtio/src/util/strings.ts

* workspace.ts
* Ports the functions for the Registry and TreeWatcher jolokia mbeans
* The response for the TreeWatcher is to call workspace.refresh()
* Allows new nodes created by async calls on target apps to be added to the JMX and Camel trees
* .../context.ts
* Adds a react ref for holding onto the selected node between renderings which allows the existing selected node to be re-selected upon a change to the underlying nodes trees
* Since both camel and JMX trees use the same instances of nodes (taken from workspace.getTree() then they can be directly selected in both trees
* Ensure the trees expand to show the node selections if the one tree happens to have not ever selected the selection before, eg. select a context in Camel Plugin then click on JMX Plugin would expand and highlight …

(#194): Implements workspace monitoring of tree server changes

---

packages/hawtio/src/plugins/connect/ConnectPreferences.tsx
packages/hawtio/src/plugins/connect/__mocks__/jolokia-service.ts
packages/hawtio/src/plugins/connect/jolokia-service.test.ts
packages/hawtio/src/plugins/connect/jolokia-service.ts
packages/hawtio/src/setupTests.ts

There is a bug in Connect preferences/Jolokia service visible in the downstream main Hawtio distribution that Hawtio and Camel MBeans are dropped from the loaded MBean tree. This fixes the bug.

fix(connect): Jolokia service not setting right max collection size to requests

---

app/src/examples/index.ts
packages/hawtio/src/index.ts
packages/hawtio/src/plugins/connect/index.ts
packages/hawtio/src/plugins/index.ts
packages/hawtio/src/preferences/index.ts
packages/hawtio/src/ui/page/HawtioHeader.tsx
packages/hawtio/src/ui/page/HawtioPage.tsx

fix #229 and supercede #232
Splitting packages for exposing plugin API (#232) seems to be too much by introducing a bit too much complexity to the project. And there are issues with splitting it: 1) util module, 2) circular dependency between core and plugins, thus it couldn't be cleanly achieved with the current codebase.
For now, we can just expose every required API from `@hawtio/react` (this pull req) to move things forward. We can revisit the plugin API exposure issue later once we've learned better about the problem space.

feat(plugin): export plugin API to plugin developers

---

packages/hawtio/src/plugins/camel/CamelTreeView.tsx
packages/hawtio/src/plugins/jmx/JmxTreeView.tsx

Quick fix to unblock https://github.com/hawtio/hawtio/issues/2826.
I was unable to find how it was generated in other version actually, but from inspecting the other version, it seems to just be concatenating the parents.
This is just a quick fix and will need to be refactored:
- The ideal is to maybe change the IDs generated by the MBeans to be like this, but I was unable to find this info for JMX, only for Camel (in the Camel Tree Processor).
- I don't know if those ids are used for something else
- If there is no search done I'm quite sure I'm mutating the MBeans themselves as well when doing this. While navigating a bit through the app, I didn't find any bugs though.
- As the tree comes from patternfly, there was no way to just change the component to have another logic in the tag, …

fix(test): Normalized tags for testing

---

packages/hawtio/src/plugins/camel/CamelTreeView.tsx
packages/hawtio/src/plugins/camel/camel-content-service.test.ts
packages/hawtio/src/plugins/camel/routes-service.test.ts
packages/hawtio/src/plugins/camel/routes-service.ts
packages/hawtio/src/plugins/camel/tree-processor.test.ts
packages/hawtio/src/plugins/camel/tree-processor.ts
packages/hawtio/src/plugins/jmx/JmxTreeView.tsx
packages/hawtio/src/plugins/shared/tree/node.test.ts
packages/hawtio/src/plugins/shared/tree/node.ts
packages/hawtio/src/plugins/shared/tree/tree.test.ts
packages/hawtio/src/plugins/shared/tree/tree.ts
packages/hawtio/src/plugins/shared/workspace.test.ts
packages/hawtio/src/util/jolokia.test.ts
packages/hawtio/src/util/jolokia.ts

Address hawtio/hawtio#2826
Now we hide HTML `id` generation behind `MBeanNode` constructor and have it autogenerated based on its name and parent, since the `id` is not some logical identifier for a node, but the HTML `id` that is rendered in HTML. We don't need to care about assigning `id` when creating a node. But their consistency is required for e2e testing downstream at the hawtio standalone project.

fix(jmx,camel): consistent tree node id generation for e2e testing

---

app/craco.config.js
packages/hawtio/package.json
packages/hawtio/src/plugins/camel/CamelContent.tsx
packages/hawtio/src/plugins/camel/endpoints/SendMessage.tsx
packages/hawtio/src/plugins/camel/endpoints/endpoints-service.ts
packages/hawtio/src/plugins/camel/tree-processor.ts
yarn.lock

close #181 
Added new Send message page:
- monaco editor with XML and JSON syntax, 
- added formatting the message 
- added context property for mbeans to easily retrieve the context

feat: Add Send message page for the endpoint

---

packages/hawtio/src/plugins/camel/CamelContent.tsx
packages/hawtio/src/plugins/camel/camel-content-service.ts
packages/hawtio/src/plugins/camel/endpoints/BrowseMessages.tsx
packages/hawtio/src/plugins/camel/endpoints/endpoints-service.ts

Adds message table with pagination and simple filtering 
Compared the old hawtio I used `exchangeId` I also added pagination and the substring of the Message body.
What is still missing:
-  multiple filters
-  forwarding of the messages

feat: Add Browse page for the endpoint

---

packages/hawtio/src/plugins/camel/CamelContent.css
packages/hawtio/src/plugins/camel/CamelContent.tsx
packages/hawtio/src/plugins/camel/CamelTreeView.test.tsx
packages/hawtio/src/plugins/camel/CamelTreeView.tsx
packages/hawtio/src/plugins/camel/camel-content-service.ts
packages/hawtio/src/plugins/camel/context.ts
packages/hawtio/src/plugins/camel/contexts/ContextToolbar.tsx
packages/hawtio/src/plugins/camel/contexts/Contexts.tsx
packages/hawtio/src/plugins/camel/contexts/contexts-service.ts
packages/hawtio/src/plugins/camel/route-diagram/route-diagram-context.ts
packages/hawtio/src/plugins/camel/tree-processor.ts

* Domain node remains available in the original tree yet it is filtered out of the tree displayed in the Camel Tree View

fix(#238): Remove camel domain node from display

---

packages/hawtio/src/plugins/shared/tree/tree.ts
packages/hawtio/src/plugins/shared/workspace.ts

fixes #318.
Main cause was to introduce asynchronous element into `camelTreeProcessor`, so I updated the populating tree to be async.

fix(#318): fix synchronisation with the populating the tree

---

packages/hawtio/src/plugins/shared/operations/OperationForm.css
packages/hawtio/src/plugins/shared/operations/OperationForm.tsx
packages/hawtio/src/plugins/shared/operations/operation-service.ts
packages/hawtio/src/plugins/shared/operations/operation.ts

Closes #311 
Moved the logic for string representation of the result value to the component which has the context about the return type.
Also added return type hint to the operation so users know what they should expect when executing an operation:

fix(#311) consider operation result type for printing output

---

packages/hawtio/src/plugins/connect/jolokia-service.ts

If nothing was found, Promise was never resolved which led to block of tree processing and hawtio coudln't run. @tadayosi does this work for you? I'm not sure if it's possible to use some 'onError' callback so I fixed it this way.

fix: Add dummy success callbacks in dummy-jolokia methods

---

packages/hawtio/src/plugins/camel/CamelContent.tsx
packages/hawtio/src/plugins/camel/camel-content-service.ts
packages/hawtio/src/plugins/camel/endpoints/EndpointStats.test.tsx
packages/hawtio/src/plugins/camel/endpoints/EndpointsStats.tsx
packages/hawtio/src/plugins/camel/endpoints/endpoints-service.ts

Add component test to cover rendering EndpointStats component.
closes #282 
Filtering:

feat(camel-plugin): Add 'Endpoint (in/out)' view into the camel plugin

---

packages/hawtio/src/plugins/connect/jolokia-service.test.ts
packages/hawtio/src/plugins/connect/jolokia-service.ts
packages/hawtio/src/plugins/rbac/tree-processor.ts
packages/hawtio/src/plugins/shared/workspace.ts
packages/hawtio/src/util/jolokia.ts

* jolokia-service
* Refactor checkListOptimisation function to reject correctly on error
* In case of plain jolokia javaagent, no hawtio:security mbean exists so function will be exepcted to fail
* Ensures the error fn is properly implemented & rejects correctly
* Ensures that implemented list() function also implements error function
* jolokia.ts
* Adds onListSucccessAndError to support custom error implementations
* tree-processor.ts
* In the event of no acl mbean, stop the bulk requests failing to identify any RBAC operations

fix(#350): Fixes connection errors when running against plain jolokia

---

packages/hawtio/src/plugins/camel/endpoints/EndpointStats.test.tsx
packages/hawtio/src/plugins/camel/endpoints/EndpointsStats.tsx

Makes table sortable as it was in the legacy hawtio.
Related to #352

feat(endpoints-stats): make table sortable

---

packages/hawtio/src/plugins/camel/CamelTreeView.css
packages/hawtio/src/plugins/jmx/JmxTreeView.css

Implements #262 . Implemented in Camel and JMX view
Before
After
Also working in JMX tree
Although one side effect is that on very small screens the text is outright hidden,
but the alternative is to have it all outside which looks bad. 
I feel like in that case the user should just adjust the slider to increase the space.

feat(#262): Prevent overlay on smaller screens

---

packages/hawtio/src/plugins/camel/CamelContent.css

Fixes #268 
@phantomjinx Do you know why you hard-set the value to auto on the css? I checked all the camel pages to see if the change breaks something but it'd be great to know if you remember what was it so I can double check.
In any case, using inherit should be extra safe instead of removing the rule altogether

fix(#268): Removes overflow auto and sets to inherit so selects in card can go over the div boundary

---

packages/hawtio/src/plugins/camel/endpoints/BrowseMessages.test.tsx
packages/hawtio/src/plugins/camel/endpoints/BrowseMessages.tsx

move message selector to the modal header as is in legacy hawtio
fix: #338

fix(BrowseMessages): Create new component with arrows instead of using patternfly's numberInput

---

app/craco.config.js
packages/hawtio/src/plugins/connect/connect-service.ts

* The proxy url in hawtio-backend includes the context in the form: host:port/hawtio/proxy/
* The hawtio-backend-middleware provides an express server that makes the backend available via the '/proxy' url
* Rather than trying to redo the hawtio-backend-middleware, aligns the dev server with the hawtio-backend by setting up a 'proxy' to rewrite 'hawtio/proxy' and point to '/proxy'
* connect-service.ts
* Adds the base path to the proxy url creation

fix(proxy): aligns the dev server proxy url with the real backend

---

packages/hawtio/src/plugins/camel/endpoints/BrowseMessages.test.tsx
packages/hawtio/src/plugins/camel/endpoints/BrowseMessages.tsx

Added suggestions to forward message text input as in legacy hawtio:

feat(ForwardMessage): Add typeahead suggestions to forward message input

---

packages/hawtio/src/plugins/camel/endpoints/BrowseMessages.tsx
packages/hawtio/src/plugins/camel/endpoints/InputWithSuggestions.tsx
packages/hawtio/src/plugins/camel/endpoints/SendMessage.tsx
packages/hawtio/src/plugins/camel/endpoints/exchange-headers-camel-model.json

also: 
- manually created exchange headers definitions into the `camel-model` 
- reused input with suggestions from the `BrowseMessages` component

Feat: Add  suggestion's for a header name input

---

packages/hawtio/package.json
packages/hawtio/src/plugins/camel/camel-content-service.ts
packages/hawtio/src/plugins/shared/attributes/AttributeModal.tsx
packages/hawtio/src/plugins/shared/operations/Operations.tsx
packages/hawtio/src/plugins/shared/tree/node.ts
yarn.lock

Now JMX Operations tab crashes when looking at a mbean that has no operations. jolokia.js should be updated so that we expect `attr` and `op` are indeed optional at type level.

Fix jmx operations error

---

packages/hawtio/src/plugins/camel/CamelContent.tsx
packages/hawtio/src/plugins/camel/debug/Debug.tsx
packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.css
packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.tsx
packages/hawtio/src/plugins/camel/route-diagram/context.ts
packages/hawtio/src/plugins/camel/route-diagram/visualization-service.ts
packages/hawtio/src/plugins/camel/trace/Trace.tsx

* Removed `selectedNode` from route diagram context; we have been trying to merge the react contexts for each submodule, but I think it's perfectly fine to use multiple react contexts at the same time. React contexts are just a convenient way to use states without passing them as props for cascading sub components. So, ideally we should have normally three contexts for each sub component: the Hawtio context (if any), the root plugin context (camel), and the context specific to a sub component (e.g. route diagram context). Node selection should be provided by the root plugin context.
* Declare return types for the visualization service
* Some other code changes to align with the styles of the other components
Initially I tried to remove the route diagram context and move them to component …

refactor(camel): refactor Camel RouteDiagrams view

---

packages/hawtio/src/plugins/camel/CamelContent.tsx
packages/hawtio/src/plugins/camel/camel-service.ts
packages/hawtio/src/plugins/camel/endpoints/SendMessage.tsx
packages/hawtio/src/plugins/camel/endpoints/endpoints-service.ts
packages/hawtio/src/plugins/camel/routes-service.ts
packages/hawtio/src/plugins/shared/tree/node.ts

Applies `hasInvokeRights` check to the rest of the Camel nav items.
Should fix #134.
Over time, we might find more places where we should fine-control visibility of UI components on Hawtio, but we can tackle them later on demand.

feat(camel,rbac): apply RBAC to Camel views (2)

---

packages/hawtio/package.json
packages/hawtio/src/plugins/camel/camel-service.test.ts
packages/hawtio/src/plugins/camel/camel-service.ts
packages/hawtio/src/plugins/camel/endpoints/AddEndpointWizard.tsx
packages/hawtio/src/plugins/camel/endpoints/SendMessage.tsx
packages/hawtio/src/plugins/camel/endpoints/context.ts
packages/hawtio/src/plugins/camel/endpoints/endpoints-service.test.ts
packages/hawtio/src/plugins/camel/endpoints/endpoints-service.ts
packages/hawtio/src/plugins/camel/index.ts
packages/hawtio/src/plugins/camel/properties/Properties.tsx
packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.tsx
packages/hawtio/src/plugins/camel/route-diagram/visualization-service.test.ts
packages/hawtio/src/plugins/camel/route-diagram/visualization-service.ts
packages/hawtio/src/plugins/camel/routes-service.ts
packages/hawtio/src/plugins/camel/schema-service.test.ts
packages/hawtio/src/plugins/camel/schema-service.ts
packages/hawtio/src/plugins/camel/tree-processor.test.ts
packages/hawtio/src/plugins/camel/tree-processor.ts
packages/hawtio/src/plugins/rbac/tree-processor.ts
packages/hawtio/src/plugins/shared/workspace.ts
packages/hawtio/src/util/objects.test.ts
packages/hawtio/src/util/strings.test.ts
packages/hawtio/src/util/strings.ts
yarn.lock

Fix #242
This fix only switches the camel definition model between v3 and v4 based on the `camelVersion` attribute value for the selected context node. That means we can mix up different versions of Camel within a single app if we have multiple contexts. It looks like the Camel plugin implementation is flexible enough that we don't need to copy a different version of the plugin for Camel v4 support.
So from now on, all the code in Camel plugin should fetch the Camel schema model from `camelService.getCamelModel(node: MBeanNode)` and should not directly reference `@hawtio/camel-model-v3` or  `@hawtio/camel-model-v4`. This function should serve as the central point for getting the appropriate Camel model.
Please check if my assumption is not wrong.

feat(camel): support multi Camel versions v3 & v4

---

.github/workflows/e2e-test.yml
README.md

Runs E2E tests from hawtio/hawtio on PRs. Adds ability to specify a different branch by specifying it using `branch: <branch>` in the PR description. Otherwise prebuilt 3.x image is used. 
https://github.com/hawtio/hawtio-next/pull/450 <- Testing PR so you can see it working.
Related to https://github.com/hawtio/hawtio/pull/2902

ci: Run E2E tests on PRs

---

packages/hawtio/src/index.ts

This is required for hawtio-online since we need to connect the osAuthService to the userService

chore: exports the auth module for use with external clients

---

packages/hawtio/tsconfig.json
packages/hawtio/tsup.config.ts

Fix #474
@phantomjinx It appears this is enough to fix the warning. Please check.

fix(build): fix tsconfig.json target warning from esbuild

---

packages/hawtio/src/ui/page/HawtioHeader.css
packages/hawtio/src/ui/page/HawtioHeader.tsx

Right now, when a custom brand logo with a big size is provided via `hawtconfig.json`, it's rendered full size in the header and consumes a lot of space on the console.

fix(ui): HAWNG-11 custom brand logo must not be greater than height=50px

---

packages/hawtio/src/plugins/camel/camel-service.test.ts
packages/hawtio/src/plugins/camel/camel-service.ts
packages/hawtio/src/plugins/camel/endpoints/endpoints-service.ts
packages/hawtio/src/plugins/camel/exchanges/exchanges-service.ts
packages/hawtio/src/plugins/camel/properties/Properties.tsx
packages/hawtio/src/plugins/camel/properties/properties-service.ts
packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.tsx
packages/hawtio/src/plugins/camel/routes-service.test.ts
packages/hawtio/src/plugins/camel/routes-service.ts
packages/hawtio/src/plugins/camel/routes/Source.tsx
packages/hawtio/src/plugins/camel/routes/routes-service.ts
packages/hawtio/src/plugins/camel/tree-processor.test.ts
packages/hawtio/src/plugins/camel/tree-processor.ts
packages/hawtio/src/plugins/shared/tree/node.test.ts
packages/hawtio/src/plugins/shared/tree/node.ts

refactor(shared): rename 'properties' to 'metadata' on MBeanNode

---

app/src/examples/example3/Example3.tsx
app/src/examples/example3/ToolbarItemComp.tsx
app/src/examples/example3/index.ts
packages/hawtio/src/core/core.ts
packages/hawtio/src/ui/page/HawtioHeader.tsx

This is an attempt to address the dynamic navbar that displays in hawtio-online. The toolbar dropdown is dynamic in that it changes link target, dependent on which plugin route is active. Therefore, this solution attempts to mirror this functionality.
To test, execute `yarn start` and click on `Example 3` plugin to see the newly added custom toolbar items for that plugin.
---
* core.ts
* Adds optional toolbarItems property to plugin interface
* HawtioHeader.tsx
* Picks up the plugins from the context and find the plugin that is currently being displayed. If this plugin has a toolbar item property then pick up the components into a custom toolbar group

fix: Ability to add custom toolbar items to main page nav bar

---

app/src/examples/example3/Example3.tsx
app/src/examples/example3/ToolbarItemComp.tsx
app/src/examples/example3/index.ts
packages/hawtio/src/core/core.ts
packages/hawtio/src/ui/page/HawtioHeader.tsx

* core.ts
* Some plugins require their header items to remain displayed on the
header navbar, even though the plugin is not displayed, eg. when
click 'connect' in hawtio-online with the discover plugin, a new window
displays hawtio-app showing the connection JMX data. This new window
still benefits from having the discover plugin dropdown list present so
that other pods or console can be accessed without returing to the
discover plugin.
* Adds a 'universal' property to Plugin structure so that an individual
plugin can state whether its header items should remain on the header
toolbar even if the rest of the plugin is not the focused-on display
* HawtioHeader.tsx
* Find all header items that are either from the focused plugin or
are marked as 'universal' to build the customized toolbar

feat: Further enhance the plugin header items extension point

---

packages/hawtio/src/plugins/index.ts
packages/hawtio/src/plugins/runtime/Metrics.tsx
packages/hawtio/src/plugins/runtime/Runtime.tsx
packages/hawtio/src/plugins/runtime/SysProps.test.tsx
packages/hawtio/src/plugins/runtime/SysProps.tsx
packages/hawtio/src/plugins/runtime/ThreadInfoModal.tsx
packages/hawtio/src/plugins/runtime/Threads.tsx
packages/hawtio/src/plugins/runtime/globals.ts
packages/hawtio/src/plugins/runtime/help.md
packages/hawtio/src/plugins/runtime/index.ts
packages/hawtio/src/plugins/runtime/runtime-service.ts
packages/hawtio/src/plugins/runtime/types.ts

Adds Runtime plugin: with Properties, Metrics and Threads tabs:

feat(runtime): Initial Runtime plugin

---

packages/hawtio/package.json
yarn.lock

Appears to be compiling correctly.
ref: https://github.com/hawtio/hawtio-next/pull/574
#576

chore(deps): bump @types/react from 18.2.21 to 18.2.23 #576

---

packages/hawtio/src/ui/page/HawtioPage.tsx

When directly accessing to /index.html, React router doesn't treat it as root '/' so the default page resolution didn't happen. This fix changed the React router routes to explicitly redirect '/index.html' to '/'.
This fix is needed for Spring Boot 3 runtime support.

fix(ui): redirect '/index.html' to root '/'

---

packages/hawtio/src/plugins/camel/endpoints/EndpointsStats.tsx
packages/hawtio/src/plugins/camel/routes/CamelRoutes.tsx

fix:  Mitigate 'findDOMNode is deprecated in StrictMode.' warning in Route/Endpoins tabs by using noWrap

---

packages/hawtio/src/plugins/camel/camel-service.ts
packages/hawtio/src/plugins/camel/debug/debug-service.ts

That causes E2E tests to fail at the Hawtio 4.x branch:
https://github.com/hawtio/hawtio/actions/runs/6415179167/job/17416913036

fix(camel): getBreakpoints op for Camel BacklogDebugger changed between v3 and v4

---

packages/hawtio/src/plugins/rbac/rbac-service.ts
packages/hawtio/src/plugins/shared/jolokia-service.ts
packages/hawtio/src/plugins/shared/workspace.ts

Basically, lazy-init methods that return Promise should not use async/await as otherwise we would be screwed up with subtle concurrency issues.

fix(shared): jolokia instance is created every time getJolokia() is invoked

---

.eslintrc.js
packages/hawtio/scripts/generate-camel-svg-index.js
packages/hawtio/src/core/logging.ts
packages/hawtio/src/plugins/camel/endpoints/endpoints-service.ts
packages/hawtio/src/plugins/camel/exchanges/InflightExchanges.test.tsx
packages/hawtio/src/plugins/shared/__mocks__/connect-service.ts
packages/hawtio/src/plugins/shared/__mocks__/jolokia-service.ts
packages/hawtio/src/setupTests.ts

* Uses eslint-disable-next-line to keep those instances where it makes sense to use console.[log|error]
issue #625

fix: Adds noconsole rule to guard against casual console.log msgs #625

---

packages/hawtio/src/plugins/connect/Connect.css
packages/hawtio/src/plugins/connect/Connect.tsx

fix(connect): rephrase and polish hint text for Connect plugin

---

packages/hawtio/src/plugins/shared/__mocks__/jolokia-service.ts
packages/hawtio/src/plugins/shared/jolokia-service.ts

Fix #447
Depends on hawtio/hawtio#2965, hawtio/hawtio#2966

feat(shared): jolokiaService.list() to accept path for returning partial set of MBeans

---

app/public/hawtconfig.json
packages/hawtio/src/core/config-manager.ts
packages/hawtio/src/plugins/shared/__mocks__/jolokia-service.ts
packages/hawtio/src/plugins/shared/jolokia-service.ts
packages/hawtio/src/plugins/shared/workspace.ts
packages/hawtio/src/ui/about/context.ts

Fix #421
With this fix, now `hawtconfig.json` is enhanced to accept `jmx` option with `workspace` in it like this:
```json
{
...
"jmx": {
"workspace": ["hawtio", "java.lang/type=Memory", "org.apache.camel", "no.such.domain"]
},
...
}
```
The `workspace` accepts either `boolean` or `string[]` and if it's set to `false` you can disable the workspace completely, which is effectively the zero preload mode requested at #421.

feat(shared): support different loading options for workspace via hawtconfig.json

---

packages/hawtio/src/plugins/camel/CamelPreferences.tsx
packages/hawtio/src/plugins/camel/camel-preferences-service.test.ts
packages/hawtio/src/plugins/camel/camel-preferences-service.ts
packages/hawtio/src/plugins/camel/debug/debug-service.ts
packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.tsx
packages/hawtio/src/plugins/camel/route-diagram/visualization-service.ts
packages/hawtio/src/plugins/camel/trace/tracing-service.ts

fix(camel): apply options from preferences

---

packages/hawtio/src/core/core.ts
packages/hawtio/src/core/hooks.ts
packages/hawtio/src/plugins/camel/index.ts
packages/hawtio/src/plugins/connect/index.ts
packages/hawtio/src/plugins/index.ts
packages/hawtio/src/plugins/jmx/index.ts
packages/hawtio/src/plugins/logs/index.ts
packages/hawtio/src/plugins/quartz/index.ts
packages/hawtio/src/plugins/runtime/index.ts

fix(camel,jmx): fix Camel plugin should precede JMX

---

packages/hawtio/src/plugins/shared/jolokia-service.ts

fix(jmx,camel): fix Operations tab crashes when used with Camel JBang

---

packages/hawtio/src/plugins/springboot/Health.tsx
packages/hawtio/src/plugins/springboot/Info.tsx
packages/hawtio/src/plugins/springboot/Loggers.tsx
packages/hawtio/src/plugins/springboot/SpringBoot.tsx
packages/hawtio/src/plugins/springboot/Trace.tsx
packages/hawtio/src/plugins/springboot/TraceView.tsx
packages/hawtio/src/plugins/springboot/index.ts
packages/hawtio/src/plugins/springboot/springboot-service.ts
packages/hawtio/src/plugins/springboot/types.ts

This PR adds a trace view into the spring-boot plugin: 
Also spring-boot service is refactored to the class, for preserving infromation about spring-boot version used.

feat(springboot-plugin): Add trace view 

---

packages/hawtio/src/util/strings.test.ts
packages/hawtio/src/util/strings.ts

fix [HAWNG-7](https://issues.redhat.com/browse/HAWNG-7)

fix(stringSorter): Compare lowercase strings to prevent incorrect string ordering.

---

packages/hawtio/src/plugins/runtime/SysProps.tsx
packages/hawtio/src/plugins/runtime/Threads.tsx

This PR is essentially move `handleSearch` logic into the separate `useEffect`. This reduces little bit a complexity and improves readability.

refactor(Runtime-plugin): refactor filtering in Threads and SysProps components

---

packages/hawtio/src/plugins/camel/context.ts

This PR expands the Camel context tree by one level, leaving `MBeans` collapsed. Resolves #665 .
@tadayosi - Apologies for the delay on this issue. There were no lint issues with the `switch` statement. Some questions:
1. Is it a problem that I've done `child.defaultExpanded = true`? This will expand all root children by one (in this case, `SampleCamel`. Or is there a particular property you want me to do a conditional check for?
2. I couldn't see an easy way to test this implementation with unit tests or E2E tests. Please let me know if there's anything you'd like for me to do in this regard for this PR.

fix(camelContext): expand tree for routes, endpoints & components

---

packages/hawtio/src/plugins/springboot/Health.tsx

This PR is fixing https://github.com/hawtio/hawtio-online/issues/270
by refactoring the Health component in the spring-boot plugin. Previously there was a `Record` to determine the corrent spans for the components, however in the openshift there is more probe components that was throwing exception. 
Now I introduced just list of the components that have 'fixed' position and rest is rendered underneath:

fix(springboot-plugin):fix exceptions when rendering components

---

app/src/examples/example2/index.ts
packages/hawtio/src/core/config-manager.test.ts
packages/hawtio/src/core/config-manager.ts
packages/hawtio/src/core/core.ts

Changes required to support branding customisation by a WAR plugin such as Artemis plugin.

fix(core): provide API for plugins to customise hawtconfig programmatically

---

app/src/examples/example2/Example2.tsx
app/src/examples/example2/index.ts
packages/hawtio/src/core/core.ts

It is because plugins may customise hawtconfig, so otherwise the customisation may be ignored.

fix(core): branding should be applied after loading plugins

---

app/src/bootstrap.tsx
packages/hawtio/src/plugins/index.ts

This allows you to assemble a custom console with a selected set of builtin plugins rather than all or nothing with registerPlugins().
This provides a downstream project with a more flexibility to use the @hawtio/react component.
Fix #788

fix(api): expose each builtin plugin's entry point to the public API

---

packages/hawtio/src/plugins/shared/PluginTreeViewToolbar.tsx

fix(HAWNG-514): Change icons for Collapse and Expand to links

---

packages/hawtio/package.json
packages/hawtio/src/plugins/camel/camel-service.test.ts
packages/hawtio/src/plugins/camel/camel-service.ts
yarn.lock

Drop support for Camel model 3.x as the 3.x versions are EOL'ed upstream.
Fix #800

feat(camel): upgrade Camel models to 4.0.4 and 4.4.0

---

packages/hawtio/src/plugins/runtime/Runtime.tsx
packages/hawtio/src/plugins/runtime/ThreadInfoModal.tsx
packages/hawtio/src/plugins/runtime/Threads.tsx

* Removed 'Actions' column header and changed button label to 'Details' with changing the button styling to the link button.
* Changed tittles and labels  to sentence case capitalization
* Removed the “Add filter” button. 
* Changed “Enable connection thread monitoring to primary button style.
* Used the label component to indicate state/status level.

fix(HAWNG-571): Runtime/Threads UX changes

---

.github/workflows/e2e-test.yml
packages/hawtio/src/plugins/connect/login/ConnectLogin.tsx

With Hawtio 4.x we have app images only for Java 21 and 17, so 11 was removed from the testing matrix. 
Also the login form when connecting now is autofocused so user can login just from their keyboard + use Enter as submit. 
(Enter as submit should work automatically in forms, but the way modals are implemented the submit button is outside the form element so it doesn't trigger the submit event)

Fix E2E workflow & improve login form UX

---

.github/workflows/e2e-test.yml

Container running on the host network doesn't respect the port mapping, so config was added for both runtimes. 
Additionally store the "app" container log in the result artifacts.

fix(ci): run on correct port on localhost for quarkus & attach app logs

---

packages/hawtio/src/plugins/shared/attributes/AttributeModal.tsx
packages/hawtio/src/plugins/shared/attributes/Attributes.tsx
packages/hawtio/src/plugins/shared/operations/OperationForm.tsx

- TableComposable for the attributes list 
- `Update`changed to `Save` 
-  Used primary detail pattern instead of modal: 
- Make attributes table scrollable so whole page isn't scrolling with the table

refactor(CLUX-495,496): Use the TableComposable for attributes and primary detail pattern instead of modal

---

packages/hawtio/src/plugins/shared/tree/node.ts
packages/hawtio/src/plugins/shared/tree/tree.test.ts
packages/hawtio/src/plugins/shared/workspace.ts

https://issues.redhat.com/browse/HAWNG-612

fix(shared): HAWNG-612 jmx tree should keep rendering even in presence of malformed mbeans

---

packages/hawtio/src/plugins/shared/attributes/attribute-service.ts
packages/hawtio/src/plugins/shared/chart/Chart.tsx

fix: #437
fix: #489
fix: #624 
In addition I added a possibility to show only charts for attributes with values actually changing in time. I also added dynamic  min value for y axis to actually show some scale. Charts should be responsive now.
Improved loading performance
`branch: mmuzikar:mmuzikar-ci-test-branch`

refactor(charts): Refactor Chart page

---

packages/hawtio/src/plugins/camel/contexts/Contexts.tsx
packages/hawtio/src/plugins/camel/exchanges/BlockedExchanges.tsx
packages/hawtio/src/plugins/camel/exchanges/InflightExchanges.tsx
packages/hawtio/src/plugins/shared/attributes/AttributeTable.tsx

I migrated tables to use TableComposable instead of old PF4 table.
Also fixed #845 by refactoring selected const to use list of strings instead Context objects. 
close #180

Migrate Contexts,Exchanges,Attributes to TableComposable 

---

packages/hawtio/src/plugins/camel/exchanges/BlockedExchanges.test.tsx
packages/hawtio/src/plugins/camel/routes/CamelRoutes.tsx

chore(Routes): Add the state label to the routes list

---

packages/hawtio/src/plugins/camel/Camel.css
packages/hawtio/src/plugins/camel/CamelContent.css
packages/hawtio/src/plugins/camel/CamelContent.tsx
packages/hawtio/src/plugins/camel/contexts/Contexts.tsx
packages/hawtio/src/plugins/camel/debug/Debug.tsx
packages/hawtio/src/plugins/camel/endpoints/BrowseMessages.tsx
packages/hawtio/src/plugins/camel/endpoints/SendMessage.tsx
packages/hawtio/src/plugins/camel/exchanges/BlockedExchanges.tsx
packages/hawtio/src/plugins/camel/exchanges/InflightExchanges.tsx
packages/hawtio/src/plugins/camel/profile/Profile.tsx
packages/hawtio/src/plugins/camel/properties/Properties.tsx
packages/hawtio/src/plugins/camel/properties/PropertiesList.tsx
packages/hawtio/src/plugins/camel/rest-services/RestServices.tsx
packages/hawtio/src/plugins/camel/trace/Trace.tsx
packages/hawtio/src/plugins/camel/trace/Tracing.css
packages/hawtio/src/plugins/jmx/Jmx.css
packages/hawtio/src/plugins/quartz/Quartz.css
packages/hawtio/src/plugins/shared/attributes/AttributeTable.css
packages/hawtio/src/plugins/shared/attributes/AttributeTable.tsx
packages/hawtio/src/plugins/shared/attributes/Attributes.tsx
packages/hawtio/src/plugins/shared/operations/Operations.tsx
packages/hawtio/src/ui/page/HawtioPage.css
packages/hawtio/src/ui/page/HawtioPage.tsx

- Set the default background to the white color 
- Set trees height to whole page 
- Replace Cards with Panels across camel-plugin components and also in Attributes and Operation shared components
Some images after the change:

refactor(camel-plugin): polish the look and feel 

---

packages/backend-middleware/src/proxy.ts
packages/hawtio/src/plugins/connect/login/ConnectLogin.tsx
packages/hawtio/src/plugins/shared/__mocks__/connect-service.ts
packages/hawtio/src/plugins/shared/connect-service.ts

https://issues.redhat.com/browse/HAWNG-487

fix(connect): HAWNG-487 apply authentication throttling to connect login

---

packages/hawtio/src/plugins/camel/CamelContent.tsx
packages/hawtio/src/plugins/camel/debug/Debug.css
packages/hawtio/src/plugins/camel/debug/Debug.tsx
packages/hawtio/src/plugins/jmx/JmxContent.tsx
packages/hawtio/src/plugins/logs/Logs.tsx
packages/hawtio/src/plugins/quartz/QuartzContent.tsx
packages/hawtio/src/plugins/quartz/jobs/Jobs.tsx
packages/hawtio/src/plugins/quartz/triggers/Triggers.tsx
packages/hawtio/src/plugins/runtime/Runtime.tsx
packages/hawtio/src/plugins/runtime/SysProps.tsx
packages/hawtio/src/plugins/runtime/Threads.tsx
packages/hawtio/src/plugins/shared/JmxContentMBeans.tsx
packages/hawtio/src/plugins/shared/attributes/Attributes.tsx
packages/hawtio/src/plugins/springboot/Health.tsx
packages/hawtio/src/plugins/springboot/Info.tsx
packages/hawtio/src/plugins/springboot/Loggers.tsx
packages/hawtio/src/plugins/springboot/SpringBoot.tsx

Similar as in #883 for the rest of the plugins:

refactor(plugins): polish the look and feel of the rest of the plugins 

---

packages/hawtio/src/plugins/camel/CamelContent.tsx
packages/hawtio/src/plugins/jmx/JmxContent.css
packages/hawtio/src/plugins/jmx/JmxContent.tsx
packages/hawtio/src/plugins/quartz/QuartzContent.css
packages/hawtio/src/plugins/quartz/QuartzContent.tsx

Add hasOverflowScroll to pageSections in JMX and Quartz.
This allows to scroll content while the tree and navigation remains static:
https://github.com/hawtio/hawtio-next/assets/6814482/d7745b0a-583f-4b27-96f9-cf39830bac3c

fix(#900): Add missing aria-labels

---

packages/hawtio/src/plugins/connect/Connect.tsx
packages/hawtio/src/plugins/connect/discover/Discover.tsx

 refactor(connect-plugin): adjust the look to be consistent with the rest of the plugins

---

packages/hawtio/src/preferences/HawtioPreferences.tsx

(cherry picked from commit c9a09dde4bf64a38c9c557530736bbe4a72bc601)

[1.2.x]refactor(preferences-plugin): adjust the look to be consistent with the rest of the plugins

---

packages/hawtio/src/plugins/shared/connect-service.ts

* Makes the switch on the ConnectionModal default to https

HAWNG-646: Default connection modal to https scheme

---

packages/hawtio/package.json
packages/hawtio/src/plugins/jmx/JmxPreferences.tsx
packages/hawtio/src/plugins/jmx/index.ts
packages/hawtio/src/plugins/logs/logs-service.ts
packages/hawtio/src/plugins/shared/__mocks__/jolokia-service.ts
packages/hawtio/src/plugins/shared/attributes/attribute-service.ts
packages/hawtio/src/plugins/shared/jmx-preferences-service.test.ts
packages/hawtio/src/plugins/shared/jmx-preferences-service.ts
packages/hawtio/src/plugins/shared/jolokia-service.ts
packages/hawtio/src/plugins/shared/operations/operation-service.ts
yarn.lock

* Upgrade jolokia.js to 2.0.3 (that supports `serializeLong` option)
* Create JMX preferences and provide `Serialize long to string` option, which can affect Jolokia requests within JMX plugin
This fix limits the `serializeLong=string` option to JMX, because the change of the bahaviour might cause unexpected errors in other plugins. JMX is a generic MBeans manipulation plugin, so it should make sense to have such an option plugin-wide.
Each plugin should decide whether it's worth applying the option or not.
Fix #292

feat(shared,jmx): support serialising long to string in JSON response from Jolokia

---

app/src/examples/example3/Example3HeaderItems.tsx
packages/hawtio/src/plugins/camel/contexts/ContextToolbar.tsx
packages/hawtio/src/plugins/camel/endpoints/EndpointsStats.tsx
packages/hawtio/src/plugins/camel/routes/CamelRoutes.tsx
packages/hawtio/src/plugins/connect/remote/Remote.tsx
packages/hawtio/src/plugins/runtime/SysProps.tsx
packages/hawtio/src/plugins/runtime/Threads.tsx
packages/hawtio/src/plugins/shared/operations/OperationForm.tsx
packages/hawtio/src/plugins/springboot/Loggers.tsx
packages/hawtio/src/plugins/springboot/TraceView.tsx
packages/hawtio/src/preferences/LogsPreferences.tsx
packages/hawtio/src/ui/page/HawtioHeader.tsx

This PR gets rid of deprecated Dropdown components from the PF4 which is now at `'@patternfly/react-core/deprecated'` with the recent ones. 
`branch: jsolovjo:e2e-tests-fix-pf5-dropdowns`

refactor(Dropdowns):Refactor the components across the hawtio to use the PF5 dropdown instead of old deprecate ones

---

packages/hawtio/src/plugins/camel/contexts/Contexts.tsx
packages/hawtio/src/plugins/camel/endpoints/BrowseMessages.tsx
packages/hawtio/src/plugins/camel/icons/CamelImageIcon.tsx
packages/hawtio/src/plugins/camel/routes/CamelRoutes.tsx
packages/hawtio/src/plugins/runtime/Threads.tsx

This PR adds missing aria-labels that caused warning in the console. Also remove defaultProps for the CamelIcon and replace it with JS defaults.
fix: #971

fix: add missing aria-labels 

---

packages/hawtio/src/plugins/camel/routes/Source.tsx
packages/hawtio/src/plugins/camel/routes/routes-service.ts

When updating the routes is enabled then the editor in the Source tab under particular route becomes writable additional control/check is shown: 
When the code is changed:
When it's saved the notification is fired and control button is changed back:

feat(camel-source): Make Source editor editable when it's enabled in the CamelContext

---

app/src/examples/example3/Example3HeaderItems.tsx
packages/hawtio/src/plugins/connect/remote/Remote.tsx
packages/hawtio/src/ui/page/HawtioHeader.tsx

Switched dropdown in the Remote.tsx to the kebab style: 
Make Page header full height: 
Make Dropdown in the example3 to have shadow and border:

Small UI fixes

---

packages/hawtio/src/plugins/camel/routes/Source.tsx

Also the save button behaviour is changed. When there is no change in the source, the button is disabled.

feat(Source): Add warning about the route being editable

---

packages/hawtio/src/plugins/runtime/runtime-service.ts

The problem I am seeing in a downstream project is while viewing the Runtime->Metrics tab, CPU load almost always shows 0.00%. What I think is going on after some digging is that Jolokia is returning 0 for SystemCpuLoad due to this problem here: https://medium.com/infobipdev/the-java-cpu-usage-observer-effect-18808b18323f
> The hidden cause of this discrepancy is the rename of the metric in JDK 14 from SystemCpuLoad to CpuLoad. The old metric was not removed, only deprecated in the API. JmxCollector pulls and publishes all available metrics, effectively calculating the same CPU usage twice in a row. The value was corrupted by merely measuring it — twice.
In the back end, [`getSystemCpuLoad()` actually just calls `getCpuLoad()`](https://github.com/openjdk/jdk/blob/5e021cbcc7a6cb30a27380950e …

fix(CPU load): Fix CPU load showing 0% in Runtime -> Metrics -> System

---

packages/hawtio/src/core/event-service.ts
packages/hawtio/src/plugins/shared/operations/OperationForm.tsx
packages/hawtio/src/ui/notification/HawtioNotification.tsx

Warning is displayed both in the dropdown and an alert gets displayed for the user to copy the text manually. 
[Peek 2024-08-29 10-16.webm](https://github.com/user-attachments/assets/dff3c4d0-23fc-4e50-ad84-c944456667e1)
Also, I tweaked the event service to be able to render any ReactNode, not just strings, but as string is also a ReactNode it just extended the uses. 
Closes #628

fix: add warning for copying not working in insecure contexts

---

packages/hawtio/src/help/HawtioHelp.tsx

Dev build connected to quarkus looks like this:
with `"disabledRoutes": ["/disabled", "/camel", "/quartz"]`:

fix: Disable help for disabled plugins

---

packages/hawtio/src/plugins/springboot/Loggers.tsx
packages/hawtio/src/plugins/springboot/TraceView.tsx

fix: https://github.com/hawtio/hawtio-next/issues/1088

fix(springboot-plugin) Fix clearAllFilters behaviour

---

packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.css
packages/hawtio/src/plugins/camel/trace/Tracing.css

Red border is NOT a part of this PR :)

fix(HAWNG-753): tweak size of the Route Diagram to fill the screen

---

.github/workflows/e2e-test.yml

Successful run can be seen here https://github.com/hawtio/hawtio-next/actions/runs/10719782751
This PR isn't running the changed workflow file

fix(ci-e2e): fix merging of test results

---

packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.css
packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.tsx
packages/hawtio/src/plugins/camel/route-diagram/visualization-service.ts

fix: [#2878](https://github.com/hawtio/hawtio/issues/2878)

fix(route-visualization): edge shoudln't be displayed when stop is used

---

packages/hawtio/src/core/core.ts
packages/hawtio/src/plugins/console-status/ConsoleStatus.css
packages/hawtio/src/plugins/console-status/ConsoleStatus.tsx
packages/hawtio/src/plugins/console-status/globals.ts
packages/hawtio/src/plugins/console-status/index.ts
packages/hawtio/src/plugins/index.ts
packages/hawtio/src/plugins/shared/workspace.ts

* Adds a status plugin for displaying errors messages if the workspace failed to load. Such errors can get lost in the console log and a blank page is the result in the client.
* workspace.ts
* If an error occurs then add them to a collection in the workspace
* Provides an api for quizzing the workspace on whether it has errored
* app-status
* Plugin that is only active if
* there is a current connection (no point in displaying if nothing has been connected to yet)
* there are no mbeans collected from the jolokia connection
* Errors were flagged from the workspace
* Assuming the plugin is active, offer a component that provides notification of the workspace *

fix: Adds better error handling of workspace loading errors

---

packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.tsx
packages/hawtio/src/plugins/camel/routes-service.ts

closes: #535
Now the routeDiagram shows correct number of messages while routes being debugged: 
Also the route diagram for the single route now displays the inflight count:

fix(RouteDiagram): Show total exchanges instead of completed

---

packages/hawtio/src/help/HawtioHelp.tsx
packages/hawtio/src/preferences/HomePreferences.tsx

`branch: jsolovjo:fix-e2e-pr-1201`
before: <img width="1636" alt="Screenshot 2024-10-31 at 15 41 07" src="https://github.com/user-attachments/assets/2fbc3d97-e3cd-4330-bd66-b1e03df03dde">
after:

[1.6.x]: refactor(Help): refactor Help page style to reflect the rest of the UI

---

packages/hawtio/src/help/HawtioHelp.tsx
packages/hawtio/src/preferences/HomePreferences.tsx

`branch: jsolovjo:fix-e2e-pr-1201` 
Before: 
After:

refactor(Help): refactor Help page style to reflect the rest of the UI

---

app/webpack.config.cjs
packages/hawtio/src/plugins/shared/__mocks__/connect-service.ts
packages/hawtio/src/plugins/shared/connect-service.ts
packages/hawtio/src/plugins/shared/jolokia-service.ts

Required by hawtio/hawtio#3731
This enhancement introduces support for the new backend API `/preset-connections` which can return a set of preset connections from the Hawtio CLI `--connection` option and automatically connecting to them.

feat(connect): enable auto-connect based on preset connections from backend

---

packages/hawtio/src/plugins/quartz/quartz-service.ts
packages/hawtio/src/plugins/quartz/triggers/TriggersManualModal.tsx

fix(quartz): fail to fire triggers manually with exception "job does not exist"

---

packages/hawtio/package.json
packages/hawtio/src/plugins/shared/operations/OperationForm.tsx
yarn.lock

fix https://github.com/hawtio/hawtio-next/issues/1316
@tadayosi please kindly take a look
Enhance JMX Operation Result Rendering
Improve handling of HTML results in JMX operations using the existing [`isResultHtml()` ](https://github.com/hawtio/hawtio-next/blob/main/packages/hawtio/src/plugins/shared/operations/OperationForm.tsx#L194) method:
- Render HTML results by default after sanitization
- Add a toggle button to switch between rendered HTML and raw text view

issue-1316 rendering html result of jmx operations

---

packages/hawtio/src/plugins/shared/connect-service.ts

The singleton jolokiaService uses the `currentConnectionId` attribute from the connect-service, which is assigned on its construction. If there is no id already in the storage then it will be null. Since Hawtio assumes a single tab (so essentially a new app) for each instance then this attribute is assigned read-only and remains its constructed value.
In an environment, like the console-plugin, the switching to show data from different pods is done by updating the current connection in the session storage. Since the connect-service is a singleton that is shared amongst all pods, this in effect requires the updating of the `currentConnectionId` , else the original data is requested and wrong data shown.
Therefore, it is necessary to update the currentConnectionId should a new pod be …

Adds ability to set the current connection in the connect-service

---

packages/hawtio/src/plugins/console-status/ConsoleStatus.tsx

In React 17 there is an assumption that components instantiate through a map loop must carry a key attribute. Without this the 'setExtraStackFrame' error occurs (see https://github.com/facebook/react/issues/20359)

Bug in ConsoleStatus - manifests in React 17

---

app/package.json
app/webpack.config.cjs
packages/hawtio/tsconfig.json
yarn.lock

- Specifies the target of ts building as 'es2015'. This is consistent with React 17 and is the target already specified in Hawtio-Online. So seemed to help with initial issues but might not be essential;
- Debugging the demo app in @hawtio/react proved particularly useful when considering the routing issues seen early on. So adding source-map generation to this app has been effective.

Changes to build configuration

---

packages/hawtio/src/plugins/camel/debug/Debug.css

There css overrides were introduced while the camel plugin was being implemented. Whether there was some difference in colour in Patternfly 4, am not sure why there were necessary. Removing causes no ill-effects in the test-app, a build of hawtio or an install of Hawtio-Online. For example, the background of the debug pane remains white.
Including them, causes an override in the hawtio-online dynamic-console-plugin which renders the Debug white while the rest of the UI is dark so it would be advantageous to remove them.

Removes overrides for background color of Route Diagram

---

app/public/hawtconfig.json
packages/hawtio/src/core/config-manager.test.ts
packages/hawtio/src/core/config-manager.ts
packages/hawtio/src/ui/page/HawtioHeader.tsx
packages/hawtio/src/ui/page/HawtioPage.tsx

Since the Hawtio-Online dynamic console plugin has much more limited space, it is necessary to re-organise the UI components. Therefore,
- Being able to show/hide the header bar. This is no longer strictly necessary as the latest version of the console plugin still makes use of the header bar but figured this option was still useful, hence its inclusion;
- Being able to hide the brand logo. This is out of place in a sub-component tab of the OCP console and takes up a significant amount of space so essential to hide it;
- Being able to hide the User dropdown. This is redundant in the OCP console since the user is displayed at the top of the console, the Preferences are integrated in the console and logout action is redundant;
- Being able to hide the sidebar. The sidebar is wide and …

Adds hawt config properties to change appearance of the header and sidebar

---

packages/hawtio/src/plugins/springboot/Health.css
packages/hawtio/src/plugins/springboot/Health.tsx
packages/hawtio/src/plugins/springboot/SpringBoot.tsx

Sets the background/padding to the PF5 style.
I also added a bit of padding to the icons as they were too close to the margin.
Without padding:
With the padding:

fix(springboot-plugin): Set background to PF5 style.

---

packages/hawtio/src/plugins/camel/CamelTreeView.css
packages/hawtio/src/plugins/jmx/JmxTreeView.css
packages/hawtio/src/plugins/quartz/QuartzTreeView.css

Fix #1380 
This is a best effort solution, setting the height of the first node of the tree list to 83% of the view height as it is similar to the height of the tree list. That allows the tree-list to have an overflow (as it has now a fixed height)
I would need to research more or do a refactor on the UI for a better solution, but it has already taken 3 days trying different things and I don't think it's worth investing more time on it.
Let me explain:
Currently, the current style breaks the size the tree list has for its contents. That's why all the page scrolls.
This is typical with lists, as they will usually overflow their container unless they have a fixed height. The typical solutions felt undesirable to use or had issues
- Height: 100% doesn't work, as the parent node doesn't have …

fix(camel, jmx, quartz): Added independent scrolling to Tree View #1380

---

packages/hawtio/src/Hawtio.tsx
packages/hawtio/src/ui/page/HawtioHeader.tsx
packages/hawtio/src/ui/page/HawtioPage.tsx

Fixes #1282 
Updates the router component to use new features found in version 7. The guidelines https://reactrouter.com/upgrading/v6
There is a new warning, but it contradicts the fixes needed for https://reactrouter.com/upgrading/v6#v7_relativesplatpath. Trying to follow it is like we had before, and breaks the page. For now I have ignored it as I think that when we upgrade to 7 it should be removed.

update(router): Upgrade router to 7 (#1282)

---

packages/hawtio/src/plugins/camel/CamelPreferences.css

Aligns tip icons next to labels according to PF5 standarts as can be seen in https://www.patternfly.org/components/forms/form/html#horizontally-aligned-labels
It will be seen as this:

fix(preferences): Tip icons next to labels (#1438)

---

packages/hawtio/src/ui/util/FilteredTable.tsx

Fixes bug where search items couldn't be removed unless they were set by changing the type of the filter.
https://github.com/user-attachments/assets/cd617ece-79f7-45aa-9361-8fb831f13e52
I'm adding @mmuzikar to the reviewers as he was the original creator of the component

fix(runtime): Search terms can be removed (#1435)

---

packages/hawtio/src/ui/util/FilteredTable.tsx

From #1435 I noticed that the only way to set a search term is by changing the type of filter. This PR allows the user to be able to add search terms pressing Enter key.
https://github.com/user-attachments/assets/71391ab2-14aa-4544-b715-fe7936bad56c

fix(runtime): Search terms can be set with enter key (#1435) (proposition)

---

packages/hawtio/src/plugins/logs/Logs.tsx
packages/hawtio/src/plugins/runtime/SysProps.tsx
packages/hawtio/src/plugins/runtime/Threads.tsx
packages/hawtio/src/plugins/shared/JmxContentMBeans.tsx
packages/hawtio/src/ui/util/FilteredTable.tsx

Fixes #1452 
Sets a new field to configure FilteredTable to add the width desired for the table. It's recommended to use it to ensure that the columns stay at a fixed width and the content is adjusted accordingly. Even then, there is no guarantees that a specially long string wont break the width but for now it seems working fine.
https://github.com/user-attachments/assets/adef98f1-9d8e-492e-be3c-b94c10a8c6a7
Also sets a width for JMXContentMBeans because that table was jumping widths while exploring through the MBeans in JMX and Camel, which looked odd.
I haven't touched other tables as they can't be filtered or paginated as far as I've seen, so the width will stay fixed for that table as all the content has already been loaded. Also, as the tables are different depending on the …

fix(runtime, logs, shared): Fixed colum width changing in tables (#1452)

---

packages/hawtio/src/plugins/connect/remote/Remote.css
packages/hawtio/src/plugins/connect/remote/Remote.tsx

Fixes toggle moving in connect when the dropdown was shown.
https://github.com/user-attachments/assets/558689c6-3315-48a0-a9d5-ca2f46aa3224
The changes fixes the issue but I wasn't able to see what was causing it:
- The style of the buttons inside actions should have a margin-right set to 0 like in the examples in PF https://www.patternfly.org/components/data-list#checkboxes-actions-and-additional-cells
- The Inspector tells me the toggle button should have margin-right set to 0, but for some reason, when it's toggled, the toggle gets a margin-right: 16px. When you turn off the toggle, the margin-right is correctly set to 0.
- Also, the connect button to the left also has this margin-right: 16px and it shouldn't have.
- There is no mention on Hawtio-next codebase of any CSS rule setting …

fix(connect): Fixed toggle moving when dropdown was shown (hawng-967)

---

packages/hawtio/src/plugins/shared/connect-service.ts

Testing through activemq artemis console.
The exception is not handled properly in the current version, see screenshot.
This also causes some issues with website/browser when developer tools are open, since it takes a lot of time to open the debug tab and the webpage in the browser can freeze.
I tested this fix with hawtio v4.4 and it works.
Please check.

fix: catch exception on http code 403 properly

---

packages/hawtio/src/plugins/connect/discover/discover-service.ts

If agent.agent_id is undefined, it should always become 'discover-undefined'. Then it should be rather simply ''.

fix(connect): HAWNG-1008 copy paste error

---

packages/hawtio/src/plugins/camel/debug/debug-service.ts
packages/hawtio/src/plugins/camel/trace/Trace.tsx
packages/hawtio/src/plugins/camel/trace/Tracing.css

Fixes: https://github.com/hawtio/hawtio/issues/3526
Update: There was a breaking change in Camel 4.5, the property needed for the BacklogTracer to show now is camel.trace.enabled = true
I have already been able to test it. Here it's how it looks.
https://github.com/user-attachments/assets/dc4c702b-5559-478e-9d0e-1c04c44c532d
Previous draft comments:
Uploading as draft to get input @tadayosi as I can't get the tab to show to see if it works.
Original task: https://github.com/hawtio/hawtio/issues/3526
I have added the new fields requested by Claus
Implemented in Hawtio React as I believe is the front end for current Hawtio version, if I should update hawtio standalone/console please tell me and I'll get with it.
The XML format I have got from: …

feat(camel): Improved tracer feature adding extra fields

---

packages/hawtio/src/Hawtio.tsx
packages/hawtio/src/core/core.ts
packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.css
packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.tsx
packages/hawtio/src/plugins/camel/route-diagram/visualization-service.ts
packages/hawtio/src/setupTests.ts

Apologies this is 2 commits for 2 issues but if they are submitted separately then one or other would have to be rebased once one was merged. Therefore, if you can indulge me and review the 2 commits separately for 1 PR, I'd appreciate it.
Commits
1.  fix: Aligns the size of the camel diagram content with parent bounds (#1543)
* When opening the route diagram, gets the bounds of the parent div and
creates the camel nodes in proportion and centres them appropriately
* RouteDiagram.tsx
* Splits the diagram component to provide an outer div with a reference
that can maintain the bound box dimensions. The inner
ReactFlowRouteDiagram is then refreshed with the correctly sized nodes
and 'onLoad' sizes the viewport correctly using the reference's bounds
before fitting the view.
2.  fix: Aligns …

Addresses both node sizing and theming of application

---

README.md
app/webpack.config.cjs

* eval-source-map is heavy on memory and not meant for production. See https://webpack.js.org/configuration/devtool
* For development, this option can be changed locally if developers require it. Most of the time, it seems people do not so disable entirely

Changes the test app source map generation to reduce the memory footprint

---

packages/hawtio/src/preferences/HomePreferences.tsx

If the hawtconfig.json has disabled the sidebar, eg. in the console-plugin, then the preference for setting the sidebar as shown/collapsed is irrelevant. Better to not display it at all.

fix: Makes the showVerticalNav preference shown only if sidebar is visible
