- package.json
- src/hawtio/auth/user-service.ts
- src/hawtio/core/bootstrap.ts
- src/hawtio/core/globals.ts
- src/hawtio/core/index.ts
- src/hawtio/core/logging.test.ts
- src/hawtio/core/logging.ts
- src/hawtio/core/plugin-loader.ts
- src/hawtio/plugins/connect/Connect.tsx
- src/hawtio/plugins/connect/ConnectPreferences.tsx
- src/hawtio/plugins/connect/connect-service.ts
- src/hawtio/plugins/connect/globals.ts
- src/hawtio/plugins/connect/jolokia-service.ts
- src/hawtio/plugins/jmx/attributes/Attributes.tsx
- src/hawtio/plugins/jmx/attributes/attribute-service.ts
- src/hawtio/plugins/jmx/globals.ts
- src/hawtio/plugins/jmx/operations/operation-service.ts
- src/hawtio/plugins/jmx/tree/tree.ts
- src/hawtio/plugins/jmx/workspace.ts
- src/hawtio/preferences/HomePreferences.tsx
- src/hawtio/preferences/LogsPreferences.tsx
- src/hawtio/preferences/context.ts
- src/hawtio/preferences/globals.ts
- src/hawtio/ui/page/context.ts
- src/hawtio/ui/page/globals.ts
- src/hawtio/util/jolokia.ts
- yarn.lock
> feat(core): implement core logging

- packages/hawtio/src/plugins/camel/tree-processor.ts
* Experiment that should not have been committed
> fix: coding error

- packages/hawtio/src/Hawtio.test.tsx
- packages/hawtio/src/help/registry.test.ts
- packages/hawtio/src/plugins/connect/__mocks__/connect-service.ts
- packages/hawtio/src/plugins/connect/__mocks__/jolokia-service.ts
- packages/hawtio/src/plugins/connect/connect-service.ts
- packages/hawtio/src/plugins/connect/index.ts
- packages/hawtio/src/plugins/connect/init.test.ts
- packages/hawtio/src/plugins/connect/init.ts
- packages/hawtio/src/plugins/connect/jolokia-service.ts
- packages/hawtio/src/plugins/shared/workspace.test.ts
> fix(connect): deactivate Connect plugin only when connection name is provided

- packages/hawtio/package.json
- packages/hawtio/src/core/event-service.test.ts
- packages/hawtio/src/core/event-service.ts
- packages/hawtio/src/core/index.ts
- packages/hawtio/src/plugins/connect/jolokia-service.ts
- packages/hawtio/src/ui/notification/HawtioNotification.tsx
- packages/hawtio/src/ui/page/HawtioPage.tsx
- yarn.lock
> feat(core,ui): toast notification for system messages and errors #66

- packages/hawtio/package.json
- packages/hawtio/src/core/config-manager.test.ts
- packages/hawtio/src/core/config-manager.ts
- packages/hawtio/src/index.ts
- yarn.lock
> feat(about): About modal with component versions updated from hawtconfig.json #27

- app/craco.config.js
fyi @mmelko @joshiraez @phantomjinx
> fix(app): redirect / to /hawtio/ for app dev server

- packages/hawtio/src/plugins/camel/index.ts
- packages/hawtio/src/plugins/camel/tree-processor.ts
- packages/hawtio/src/plugins/connect/__mocks__/jolokia-service.ts
- packages/hawtio/src/plugins/connect/index.ts
- packages/hawtio/src/plugins/connect/jolokia-service.ts
- packages/hawtio/src/plugins/index.ts
- packages/hawtio/src/plugins/rbac/globals.ts
- packages/hawtio/src/plugins/rbac/index.ts
- packages/hawtio/src/plugins/rbac/rbac-service.test.ts
- packages/hawtio/src/plugins/rbac/rbac-service.ts
- packages/hawtio/src/plugins/shared/tree/processor-registry.test.ts
- packages/hawtio/src/plugins/shared/tree/processor-registry.ts
- packages/hawtio/src/plugins/shared/tree/tree.ts
- packages/hawtio/src/util/strings.ts
Relates to #36
A new pull req will be followed for implementing the RBAC tree processor. I'm sending it early to keep merge conflicts as minimum as possible among the collaborators.
> Preliminary work for RBAC support

- packages/hawtio/src/plugins/connect/__mocks__/jolokia-service.ts
- packages/hawtio/src/plugins/connect/jolokia-service.ts
- packages/hawtio/src/plugins/rbac/index.ts
- packages/hawtio/src/plugins/rbac/rbac-service.ts
- packages/hawtio/src/plugins/rbac/tree-processor.ts
- packages/hawtio/src/plugins/shared/tree/globals.ts
- packages/hawtio/src/plugins/shared/tree/node.test.ts
- packages/hawtio/src/plugins/shared/tree/node.ts
- packages/hawtio/src/plugins/shared/tree/processor-registry.test.ts
- packages/hawtio/src/plugins/shared/tree/processor-registry.ts
- packages/hawtio/src/plugins/shared/tree/tree.test.ts
- packages/hawtio/src/plugins/shared/tree/tree.ts
- packages/hawtio/src/plugins/shared/workspace.ts
- packages/hawtio/src/util/jolokia.test.ts
- packages/hawtio/src/util/jolokia.ts
- packages/hawtio/src/util/objects.ts
- packages/hawtio/src/util/strings.test.ts
> feat(rbac): add RBAC tree processor

- packages/hawtio/src/plugins/connect/ConnectPreferences.tsx
- packages/hawtio/src/plugins/connect/__mocks__/jolokia-service.ts
- packages/hawtio/src/plugins/connect/jolokia-service.ts
- packages/hawtio/src/preferences/preferences-service.ts
Most of the wiring is done and working, as is the refresh of jolokia settings.
There is a few bugs yet that needs ironing
> feat(#28): Connect preferences

- packages/hawtio/src/plugins/connect/Connect.tsx
- packages/hawtio/src/plugins/connect/connect-service.ts
Business and component logic are ready. But I'm unable to get yarn start to run it so I suspect there is some kind of muted error somewhere even though it finishes building. I'll continue on it on monday.
> wip(#67): Import connection modal core logic

- packages/hawtio/src/plugins/connect/ConnectPreferences.tsx
> feat(connect): add confirm modal and success alert for Connect preferences reset form

- packages/hawtio/src/plugins/connect/Connect.tsx
- packages/hawtio/src/plugins/connect/ConnectImportModal.tsx
- packages/hawtio/src/plugins/connect/connect-service.ts
- packages/hawtio/src/plugins/connect/connections.ts
> feat(connect): switch to file upload for import connections modal #67

- packages/hawtio/src/plugins/camel/help.md
- packages/hawtio/src/plugins/camel/index.ts
One part of #41 . Setting this up as it is straightforward enough and it can be merged already. I'll keep working on the preferences page.
> feat(#41): Camel Help

- packages/hawtio/src/plugins/shared/attributes/AttributeTable.tsx
Adds polling to the tabular attribute table to keep its data updated.
Planed to add it together with the Chart component after seeing that the other idea got scrapped, but I thought it was better to submit the fix now.
> fix(#125): Fixed component not polling for data to keep it updated

- packages/hawtio/src/plugins/shared/attributes/AttributeTable.tsx
This is a small optimization I found after reading about the lint warning. Supposedly, every function will get reevaluated in every component render (IE, after every fetch actually). There is some other ways to go about it but I found this to be the easiest and simplest one.
The only change was moving all the functions inside constants inside `useEffect` and using the supplied value of `setAttributeTable` to avoid having to put attributeList as a dependency too.
This way the warning is fixed and is a small optimization on the table component
There is a very good explanation in this URL if you want to know more about it https://codevoweb.com/react-hook-useeffect-has-a-missing-dependency-error/?utm_content=cmp-true
> refactor(#125): Small optimization and removed eslint warning

- packages/hawtio/src/plugins/camel/CamelContent.tsx
Changed order of tabs following tadayosi's suggestion as I thought it was fine enough and it was very quick. Feel free to change or reorder it if you need it after more discussion
> refactor(#226): Changed order of tabs

- packages/hawtio/package.json
- packages/hawtio/src/plugins/camel/CamelContent.tsx
- packages/hawtio/src/plugins/camel/camel-content-service.ts
- packages/hawtio/src/plugins/camel/debug/ConditionalBreakpointModel.tsx
- packages/hawtio/src/plugins/camel/debug/Debug.css
- packages/hawtio/src/plugins/camel/debug/Debug.tsx
- packages/hawtio/src/plugins/camel/debug/MessageDrawer.tsx
- packages/hawtio/src/plugins/camel/debug/debug-service.test.ts
- packages/hawtio/src/plugins/camel/debug/debug-service.ts
- packages/hawtio/src/plugins/camel/debug/index.ts
- packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.tsx
- packages/hawtio/src/plugins/camel/route-diagram/route-diagram-context.ts
- packages/hawtio/src/plugins/camel/route-diagram/routeDiagram.css
- packages/hawtio/src/plugins/camel/route-diagram/visualization-service.ts
- packages/hawtio/src/plugins/camel/routes/CamelRoutes.tsx
- packages/hawtio/src/plugins/camel/trace/Trace.tsx
- packages/hawtio/src/plugins/camel/trace/Tracing.css
- packages/hawtio/src/plugins/camel/trace/index.ts
- packages/hawtio/src/plugins/camel/trace/tracing-service.ts
- packages/hawtio/src/util/arrays.test.ts
- packages/hawtio/src/util/arrays.ts
- packages/hawtio/src/util/xml.ts
- yarn.lock
~_Trace tab to follow if still required.~
Trace tab now included.
> The Debug Tab and View

- packages/hawtio/src/plugins/connect/index.ts
> feat(plugin): export connectService from connect plugin

- packages/hawtio/src/preferences/LogsPreferences.tsx
> chore(preferences): change logger level form from select to slider for UX

- app/craco.config.js
- packages/hawtio/package.json
- packages/hawtio/src/auth/hooks.ts
- packages/hawtio/src/auth/user-service.test.ts
- packages/hawtio/src/auth/user-service.ts
- packages/hawtio/src/plugins/auth/keycloak/globals.ts
- packages/hawtio/src/plugins/auth/keycloak/help.md
- packages/hawtio/src/plugins/auth/keycloak/index.ts
- packages/hawtio/src/plugins/auth/keycloak/keycloak-service.test.ts
- packages/hawtio/src/plugins/auth/keycloak/keycloak-service.ts
- packages/hawtio/src/plugins/auth/types.ts
- packages/hawtio/src/plugins/camel/index.ts
- packages/hawtio/src/plugins/camel/schema-service.ts
- packages/hawtio/src/plugins/connect/jolokia-service.ts
- packages/hawtio/src/plugins/index.ts
- packages/hawtio/src/ui/page/HawtioPage.tsx
- packages/hawtio/src/util/fetch.ts
- packages/hawtio/src/util/http.ts
- yarn.lock
#26 
PKCE support yet to be done.
> feat(keycloak): initial Keycloak support implementation #26

- packages/hawtio/src/plugins/shared/operations/OperationForm.tsx
closes #317
Decoupling fixed the focus loosing, and also prevented some re-renders.
> fix(#317): Fix loosing focus by decoupling the OperationExecuteForm from the OperationForm

- packages/hawtio/src/plugins/camel/endpoints/BrowseMessages.test.tsx
- packages/hawtio/src/plugins/camel/endpoints/BrowseMessages.tsx
This PR adds few component tests based on Jest and  react-testing library.
> chore: Add tests for the BrowseMessages component

- packages/hawtio/src/auth/user-service.ts
- packages/hawtio/src/plugins/auth/keycloak/index.ts
- packages/hawtio/src/plugins/auth/keycloak/keycloak-service.ts
> fix(keycloak): fix logout from keycloak

- packages/hawtio/src/help/HawtioHelp.tsx
- packages/hawtio/src/plugins/camel/CamelContent.tsx
- packages/hawtio/src/preferences/HawtioPreferences.tsx
- packages/hawtio/src/preferences/help.md
Adds possibility to render html code in help (from #327) 
fixes: #267 #327
> fix(navigation): Fix not showing active tab 

- packages/hawtio/src/plugins/camel/CamelContent.css
- packages/hawtio/src/plugins/camel/CamelContent.tsx
- packages/hawtio/src/plugins/camel/contexts/ContextToolbar.tsx
- packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.tsx
- packages/hawtio/src/plugins/jmx/JmxContent.css
- packages/hawtio/src/plugins/jmx/JmxContent.tsx
> fix(camel): stop frequent rerendering of Operations view by separating ContextToolbar

- packages/hawtio/src/plugins/connect/ConnectPreferences.tsx
- packages/hawtio/src/plugins/connect/jolokia-service.ts
Fix #337
@jsolovjo In case you are interested in how to fix it.
> fix(connect): check negative numbers in input fields for Connect Preferences

- packages/hawtio/package.json
- packages/hawtio/src/plugins/camel/CamelContent.tsx
- packages/hawtio/src/plugins/jmx/JmxContent.tsx
- packages/hawtio/src/plugins/shared/chart/Chart.tsx
- packages/hawtio/src/plugins/shared/chart/WatchableAttributesForm.tsx
- packages/hawtio/src/util/objects.test.ts
- packages/hawtio/src/util/objects.ts
- yarn.lock
> feat(#10): Chart JMX

- packages/hawtio/src/plugins/shared/operations/OperationForm.tsx
- packages/hawtio/src/plugins/shared/operations/Operations.tsx
- packages/hawtio/src/plugins/shared/operations/operation-service.ts
Implements #278 
Fixes #273 #363 
While fixing this I noticed I think there is some kind of bug in the contexts. Pages are being refreshed endlessly even when their state is not changed. Should I file a bug for this? I'm not sure if it's expected because the tree is constantly being refreshed.
> feat(#273,#363,#278): Implements additional copy buttons, bugfixes

- packages/hawtio/src/plugins/shared/chart/WatchableAttributesForm.tsx
> fix(#369):Fixes watches to modify attributes to watch correctly

- packages/hawtio/src/plugins/camel/endpoints/EndpointsStats.tsx
- packages/hawtio/src/plugins/camel/routes/CamelRoutes.test.tsx
- packages/hawtio/src/plugins/camel/routes/CamelRoutes.tsx
- packages/hawtio/src/util/objects.ts
- packages/hawtio/src/util/strings.ts
This PR adds sorting to the Route table and also add a new component tests that are covering routes rendering and sorting
> feat(Routes): Add sorting functionality to Routes table

- packages/hawtio/src/ui/page/HawtioLoading.tsx
> chore: Center the Spinner in the loading screen and add Loading message

- app/craco.config.js
Partially revert 9da77e827a6b9d67a01181f608823d3bc6ba091c
@phantomjinx Please review this to check if this still solves the proxy issue.
> refactor(app): no need for custom proxy settings for backend-middleware

- packages/hawtio/src/plugins/connect/jolokia-service.ts
- packages/hawtio/src/plugins/rbac/tree-processor.ts
- packages/hawtio/src/plugins/shared/tree/node.ts
> Fix RBAC tree processor

- packages/hawtio/src/plugins/connect/jolokia-service.ts
- packages/hawtio/src/util/jolokia.ts
So that it won't hang without resolving promises anywhere it is used.
> fix(connect): apply the same fix as #328 and #357 to all async jolokia service methods

- app/craco.config.js
- app/package.json
- yarn.lock
Same stuff as in https://github.com/hawtio/hawtio/pull/2873.
`yarn build:all` from ~ 3 min to under 1 minute :tada:
> Use esbuild plugin to speedup app build

- app/craco.config.js
- app/package.json
- packages/hawtio/package.json
- yarn.lock
Re: https://github.com/hawtio/hawtio-next/pull/402
> Bump @module-federation/utilities, fix debug

- app/public/index.html
- package.json
- packages/hawtio/src/plugins/camel/properties/property.ts
- packages/hawtio/src/plugins/camel/type-converters/type-converters-service.ts
- packages/hawtio/src/plugins/shared/operations/operation.ts
- packages/hawtio/src/preferences/preferences-service.ts
- yarn.lock
* Adds extra check to format:check so these are fixed as well.
* Supercedes https://github.com/hawtio/hawtio-next/pull/410
> chore: bump prettier to 3.0.0

- packages/hawtio/src/plugins/camel/properties/PropertiesTooltippedName.tsx
- packages/hawtio/src/plugins/camel/properties/property.ts
- packages/hawtio/src/plugins/shared/tree/node.ts
- packages/hawtio/src/plugins/shared/tree/tree.test.ts
- packages/hawtio/src/plugins/shared/tree/tree.ts
- packages/hawtio/src/util/htmls.test.ts
- packages/hawtio/src/util/htmls.ts
- packages/hawtio/src/util/jolokia.test.ts
- packages/hawtio/src/util/jolokia.ts
* fixed `findDOMNode` warning with Camel Routes view
* refactored `PropertiesTooltipppedName`
> Fix camel 1

- packages/hawtio/src/plugins/camel/routes-service.ts
- packages/hawtio/src/plugins/camel/routes/CamelRoutes.test.tsx
- packages/hawtio/src/plugins/camel/routes/CamelRoutes.tsx
- packages/hawtio/src/plugins/camel/routes/route.ts
- packages/hawtio/src/plugins/camel/routes/routes-service.ts
I know I should separate refactoring from a fix, but it turned out it's really painful for me to make the clear separation while working on small issues like this. Separating pull reqs requires extra amount of work but doesn't seem to gain so much other than earning ease for reviewers. Instead, I always make clear separation of commits between refactorings and fixes, so reviewers should be able to read each commit to see what's going on separately.
I think what's important is that some one takes care of the overall code quality and tries to improve it by constant refactoring. That shouldn't be discouraged by other project conventions.
> fix(rbac,camel): fix RBAC on Camel routes start/stop/delete actions

- packages/hawtio/src/plugins/camel/routes-service.ts
When the dumpRoutesAsXml operation was not available for some reason, the Camel plugin threw an error and caused the entire plugins loading terminated. This fixes the issue by catching the error on fetching routes xml and makes plugins loading more robust.
> fix(camel): make routes xml loading more robust

- packages/hawtio/src/plugins/camel/endpoints/endpoints-service.ts
- packages/hawtio/src/plugins/camel/tree-processor.test.ts
- packages/hawtio/src/plugins/camel/tree-processor.ts
- packages/hawtio/src/plugins/shared/tree/node.test.ts
- packages/hawtio/src/plugins/shared/tree/node.ts
- packages/hawtio/src/plugins/shared/tree/tree.test.ts
- packages/hawtio/src/plugins/shared/tree/tree.ts
> fix(shared,jmx): XNIO-2 node under XNIO folder doesn't have correct IDs

- app/craco.config.js
For testing Login page with `yarn start`.
> fix(app): make login/logout work for dev server

- .github/workflows/e2e-test.yml
> ci(e2e): trigger E2E workflows on push

- packages/hawtio/src/plugins/connect/init.test.ts
- packages/hawtio/src/plugins/connect/init.ts
> fix(connect): hide Connect when the console is in embedded mode #514

- .eslintrc.js
- packages/hawtio/package.json
- packages/hawtio/src/plugins/camel/CamelTreeView.test.tsx
- packages/hawtio/src/plugins/camel/context.ts
- packages/hawtio/src/plugins/connect/ConnectPreferences.tsx
- packages/hawtio/src/plugins/index.ts
- packages/hawtio/src/plugins/logs/Logs.tsx
- packages/hawtio/src/plugins/logs/LogsPreferences.tsx
- packages/hawtio/src/plugins/logs/globals.ts
- packages/hawtio/src/plugins/logs/help.md
- packages/hawtio/src/plugins/logs/index.ts
- packages/hawtio/src/plugins/logs/log-entry.test.ts
- packages/hawtio/src/plugins/logs/log-entry.ts
- packages/hawtio/src/plugins/logs/logs-service.test.ts
- packages/hawtio/src/plugins/logs/logs-service.ts
- packages/hawtio/src/plugins/shared/tree/node.test.ts
- packages/hawtio/src/plugins/shared/tree/node.ts
- packages/hawtio/src/plugins/shared/tree/tree.test.ts
- packages/hawtio/src/plugins/shared/tree/tree.ts
- packages/hawtio/src/plugins/shared/workspace.test.ts
- packages/hawtio/src/plugins/shared/workspace.ts
- packages/hawtio/src/preferences/HawtioPreferences.tsx
- packages/hawtio/src/util/htmls.ts
- packages/hawtio/src/util/strings.test.ts
- packages/hawtio/src/util/strings.ts
- yarn.lock
Fix #153
[Screencast from 2023-09-04 13-50-12.webm](https://github.com/hawtio/hawtio-next/assets/156692/04fd0ce9-2f18-43d6-a9e0-ef63f61fd56b)
> feat(logs): initial Logs plugin

- .github/workflows/e2e-test.yml
Passing run here: https://github.com/hawtio/hawtio-next/actions/runs/6377727493
> ci(e2e): Stabilize E2E tests

- app/src/examples/example3/Example3HeaderItems.tsx
- packages/hawtio/src/plugins/camel/endpoints/EndpointsStats.tsx
- packages/hawtio/src/plugins/camel/routes/CamelRoutes.tsx
> Fix: Remote tooltips to avoid #570

- app/public/hawtconfig.json
- packages/hawtio/src/core/config-manager.ts
- packages/hawtio/src/ui/page/HawtioHeader.css
- packages/hawtio/src/ui/page/HawtioHeader.tsx
Required for https://issues.redhat.com/browse/HAWNG-11
> feat(ui): HAWNG-11 enable showing app name in header title via hawtconfig.json

- packages/hawtio/src/core/config-manager.ts
- packages/hawtio/src/core/core.ts
- packages/hawtio/src/plugins/camel/CamelTreeView.test.tsx
- packages/hawtio/src/plugins/camel/debug/debug-service.test.ts
- packages/hawtio/src/plugins/camel/endpoints/BrowseMessages.test.tsx
- packages/hawtio/src/plugins/camel/endpoints/endpoints-service.test.ts
- packages/hawtio/src/plugins/camel/exchanges/BlockedExchanges.test.tsx
- packages/hawtio/src/plugins/camel/exchanges/InflightExchanges.test.tsx
- packages/hawtio/src/plugins/camel/exchanges/exchanges-service.test.tsx
- packages/hawtio/src/plugins/camel/tree-processor.test.ts
- packages/hawtio/src/plugins/camel/type-converters/TypeConvertersStatistics.test.tsx
- packages/hawtio/src/plugins/camel/type-converters/type-converters-service.test.tsx
- packages/hawtio/src/plugins/rbac/rbac-service.test.ts
- packages/hawtio/src/plugins/rbac/rbac-service.ts
- packages/hawtio/src/plugins/shared/__mocks__/jolokia-service.ts
- packages/hawtio/src/plugins/shared/jolokia-service.test.ts
- packages/hawtio/src/plugins/shared/jolokia-service.ts
- packages/hawtio/src/plugins/shared/tree/node.test.ts
- packages/hawtio/src/plugins/shared/tree/tree.test.ts
- packages/hawtio/src/plugins/shared/workspace.test.ts
- packages/hawtio/src/plugins/shared/workspace.ts
- packages/hawtio/src/ui/login/HawtioLogin.tsx
- packages/hawtio/src/ui/page/HawtioPage.tsx
* Applied lazy loading more strictly
* Removed potential issues with promise resolutions
* Test enhancements
FYI @phantomjinx
> fix: issues related to previous enhancement on HawtioLogin #594

- packages/hawtio/src/plugins/rbac/rbac-service.test.ts
- packages/hawtio/src/plugins/rbac/rbac-service.ts
- packages/hawtio/src/plugins/rbac/tree-processor.ts
- packages/hawtio/src/plugins/shared/__mocks__/jolokia-service.ts
- packages/hawtio/src/plugins/shared/attributes/AttributeModal.tsx
- packages/hawtio/src/plugins/shared/attributes/Attributes.tsx
- packages/hawtio/src/plugins/shared/attributes/attribute-service.ts
- packages/hawtio/src/plugins/shared/jolokia-service.test.ts
- packages/hawtio/src/plugins/shared/jolokia-service.ts
- packages/hawtio/src/plugins/shared/operations/operation-service.ts
> feat(jmx): support writing attributes for writable attributes (RW)

- app/package.json
- packages/hawtio/src/core/core.test.ts
- packages/hawtio/src/core/core.ts
- packages/hawtio/src/plugins/connect/Connect.tsx
- packages/hawtio/src/plugins/connect/index.ts
- packages/hawtio/src/plugins/connect/init.ts
- packages/hawtio/src/plugins/connect/login/ConnectLogin.tsx
- packages/hawtio/src/plugins/shared/__mocks__/connect-service.ts
- packages/hawtio/src/plugins/shared/connect-service.ts
- packages/hawtio/src/plugins/shared/jolokia-service.ts
- packages/hawtio/src/plugins/shared/workspace.ts
- yarn.lock
> feat(connect): support connecting to authenticated Jolokia endpoints

- README.md
- app/package.json
- package.json
- packages/hawtio/package.json
- yarn.lock
> chore(deps): upgrade to TypeScript 5

- packages/hawtio/src/plugins/camel/camel-service.ts
- packages/hawtio/src/plugins/camel/debug/debug-service.ts
> fix(camel): debug breakpoint suspension doesn't work with Camel v4

- packages/hawtio/src/plugins/shared/connect-service.ts
1. I added additional check of the protocol to be only `http` or `https` to ensure no suspicious "protocols" as `javascript, livescript` will be executed 
2. add double check if hostname and port for the redirect is the same as origin
3.  added aditional encodeURI for the url
4. added decodeURI when retrieving `window.location.href` 
I tested this with both remote connect to localhost and to other host on the lan.
> feat: add URI encoding and additional check for the redirect to prevent XSS

- app/public/branding-example.css
- packages/hawtio/src/core/config-manager.ts
> fix(core): branding css cannot override PatternFly styles with :root selector

- packages/hawtio/src/plugins/runtime/SysProps.tsx
- packages/hawtio/src/plugins/runtime/Threads.tsx
* fixed Clear all filters behaviour
*  Removed Add Filter button and added this functionality to the Attribute selector 
* Changed 'Search ...' placeholder to 'Filter by {attribute}'
>  fix(HAWNG-572): Runtime/System properties UX changes

- .github/workflows/e2e-test.yml
> ci: switch to default branch 4.x

- app/craco.config.js
Potentially fixes the E2E failures.
> fix(ci): disable OIDC for app

- packages/hawtio/src/plugins/shared/attributes/Attributes.tsx
> fix(#852): Make Attributes table sortable

- packages/hawtio/jest.config.ts
- packages/hawtio/jsdom-test-env.ts
- packages/hawtio/src/util/objects.ts
> refactor(util): use structuredClone instead of JSON stringify/parse idiom for cloning objects

- packages/hawtio/package.json
- packages/hawtio/src/plugins/shared/jolokia-service.ts
- packages/hawtio/src/plugins/shared/tree/node.ts
- yarn.lock
> chore(deps): update jolokia.js to 2.0.1

- packages/hawtio/src/plugins/camel/debug/MessageDrawer.tsx
- packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.css
- packages/hawtio/src/plugins/camel/trace/Trace.tsx
- packages/hawtio/src/plugins/camel/trace/Tracing.css
> fix(#905): Polish the Trace view of the camel plugin

- packages/hawtio/src/plugins/camel/debug/MessageDrawer.tsx
- packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.css
- packages/hawtio/src/plugins/camel/routes/Source.tsx
- packages/hawtio/src/plugins/camel/trace/Trace.tsx
- packages/hawtio/src/plugins/camel/trace/Tracing.css
- packages/hawtio/src/plugins/connect/Connect.tsx
- packages/hawtio/src/plugins/connect/discover/Discover.tsx
Backport of PRs:
- source editor dynamic height: https://github.com/hawtio/hawtio-next/pull/920
-  the Trace view: 
- https://github.com/hawtio/hawtio-next/pull/908
connect-plugin:
-  https://github.com/hawtio/hawtio-next/pull/919
> Backport of the rest UI fixes missing in the 1.2

- packages/hawtio/src/preferences/HawtioPreferences.tsx
> refactor(preferences-plugin): adjust the look to be consistent with the rest of the plugins

- packages/hawtio/src/plugins/runtime/Metrics.tsx
- packages/hawtio/src/plugins/runtime/runtime-service.ts
- packages/hawtio/src/plugins/runtime/types.ts
> fix(Runtime-metrics): fix incorrect memory conversions

- packages/hawtio/src/plugins/camel/endpoints/SendMessage.tsx
> fix(camel-plugin): Catch the exception when formatting the message and throw the  error notification

- packages/hawtio/src/plugins/quartz/scheduler/Scheduler.tsx
> fix(Quartz): Remove actions= from the tittle of the cards

- packages/hawtio/package.json
- packages/hawtio/src/plugins/camel/camel-service.test.ts
- packages/hawtio/src/plugins/camel/camel-service.ts
- yarn.lock
> feat(camel): update supported Camel models to 4.4.x and 4.8.x

- packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.css
- packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.tsx
closes: https://github.com/hawtio/hawtio/issues/3460
> feat(routeDiagram): Add IDs to the nodes

- packages/hawtio/src/plugins/camel/route-diagram/RouteDiagram.tsx
- packages/hawtio/src/plugins/camel/routes-service.ts
backport of https://github.com/hawtio/hawtio-next/pull/1181
> [1.6.x] fix(RouteDiagram): Show total exchanges instead of completed 

- packages/hawtio/src/plugins/shared/connect-service.ts
> fix(connect): 'con=' parameter should also accept connection name

- packages/hawtio/src/plugins/shared/tree/node.ts
> fix(shared): fix handling null desc in jmx domain

- packages/hawtio/src/plugins/camel/CamelContent.tsx
- packages/hawtio/src/plugins/camel/context.ts
> fix(camel): default view should be Route Diagram

- packages/hawtio/src/plugins/camel/context.ts
> fix(camel): newly added endpoint not shown in the endpoints view

- packages/hawtio/src/plugins/camel/context.ts
> fix(camel): start/stop routes in Routes redirects to Route Diagram tab

- packages/hawtio/src/plugins/camel/CamelPreferences.css
- packages/hawtio/src/ui/util/FilteredTable.tsx
Fixes for #1435, #1438 to be added to the release
https://github.com/hawtio/hawtio-next/pull/1449
https://github.com/hawtio/hawtio-next/pull/1450
https://github.com/hawtio/hawtio-next/pull/1451
> fix(preferences, runtime): Fixed icon placements to the left. Fixed search terms not being able to be removed. (#1435, #1438)

- packages/hawtio/src/plugins/logs/Logs.tsx
- packages/hawtio/src/plugins/runtime/SysProps.tsx
- packages/hawtio/src/plugins/runtime/Threads.tsx
- packages/hawtio/src/plugins/shared/JmxContentMBeans.tsx
- packages/hawtio/src/ui/util/FilteredTable.tsx
> fix(runtime, logs, shared): Fixed colum width changing in tables (#1452) [1.9.x]

- packages/hawtio/src/plugins/runtime/Metrics.tsx
- packages/hawtio/src/util/objects.test.ts
- packages/hawtio/src/util/objects.ts
> fix(runtime): Use DescriptionList in Metrics (#1437) [1.9.x]

- packages/hawtio/src/plugins/connect/remote/Remote.css
- packages/hawtio/src/plugins/connect/remote/Remote.tsx
> fix(connect): Fixed toggle moving when dropdown was shown (hawng-967) [1.9.x]

- packages/hawtio/src/plugins/shared/jolokia-service.test.ts
- packages/hawtio/src/plugins/shared/tree/node.ts
Fix https://github.com/hawtio/hawtio-next/issues/1349
handling nullable desc in JMX JSON response
test with such response
> issue-1349 handling nullable desc

- packages/hawtio/src/plugins/quartz/jobs/Jobs.css
- packages/hawtio/src/plugins/quartz/jobs/Jobs.tsx
- packages/hawtio/src/plugins/springboot/TraceView.tsx
- packages/hawtio/src/ui/util/FilteredTable.tsx
Fixes #1529
Refactors component to use FilteredTable component
It also fixes a bug introduces on Quartz > Job refactor, now it's css only applies to that page instead to every FilteredTable (I thought CSS was local to component in React???? I have to double check this)
> refactor(spring-boot): Refactored to use Filtered Table (#1529)

- packages/hawtio/src/plugins/camel/routes-service.test.ts
- packages/hawtio/src/plugins/camel/routes-service.ts
* If an application has multiple routes and grouped then a group node will sit between the route nodes used for diagramming and the Routes node than has access to the statistics XML. This means the Routes node is not selected, the context node not found and an undefined mbean used for retrieving the XML.
* Since the function must support both the Routes diagram and Route diagrams, uses a while loop to traverse up the tree to the Routes node.
* Adds a iteration limit on the loop as a safety feature in case the tree has in same way become cyclical, thereby avoiding possiblity of an infinite loop.
> Fix: Handles route statistics in multi route applications (#1570)

- app/package.json
- packages/backend-middleware/package.json
- packages/hawtio/package.json
- packages/hawtio/src/core/event-service.test.ts
- packages/hawtio/src/help/registry.test.ts
- packages/hawtio/src/plugins/shared/tree/processor-registry.test.ts
- packages/hawtio/src/preferences/registry.test.tsx
- yarn.lock
Fixes #1568 
Branches from and fixes #1563 
Good to merge now!
> fix(test): Fixes deprecated code upgrading to jest 30e
